from __future__ import annotations

from typing import Protocol


class NotifierPort(Protocol):
    async def send_open(self, message: str) -> None: ...
    async def send_close(self, message: str) -> None: ...
    async def send_error(self, message: str) -> None: ...
